logging:
  level:
    org.springframework.data.couchbase.repository.query: DEBUG
server:
  port: 9300
spring:
  application:
    name: springboot-couchbase
  data:
    couchbase:
      auto-index: true