logging:
  level:
    org.springframework.data.couchbase.repository.query: DEBUG
spring:
  application:
    name: springboot-couchbase
  data:
    couchbase:
      auto-index: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  tokenValidity: '3600000'
  signingKey: mskara

#config:
#  couchbase:
#    host: ''
#    username: ''
#    password: ''
#    bucketName: ''
